spring:
  datasource:
    url: jdbc:mysql://localhost:53935/flowstate
    driverClassName: com.mysql.cj.jdbc.Driver
    username: flowuser
    password: flowpass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
